# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eda5af387e4f0d1389dbd1fb28adeddd6148e3542bdb38b7322ba4ac5426b1cabc861e12154c3577022b00defb28a652be672fbe78911107724bb97e113cf306

test:
  secret_key_base: a58bb59cbdc96ff89615f0321726c75ea7a8e2da7b9b7c79d74a4121cd3855fcadf401ba96a9e16b3b8af5ce585d19de851ba6b0e4f5f846ba55014d3fb1cb36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
